[tool.poetry]
name = "project-template"
version = "0.1.0"
description = ""
authors = ["Alberto G Pascoe <agonzalpascoe@gmail.com>"]
readme = "README.md"
packages = [{include = "project-template"}]

[tool.poetry.dependencies]
python = "^3.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
